// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM4MUpiszh2AFTR6H7y6DYZeYfBOC2FPA',
    appId: '1:903771649579:web:077c3cd2dc4892d9db5c6e',
    messagingSenderId: '903771649579',
    projectId: 'pw-f-crud',
    authDomain: 'pw-f-crud.firebaseapp.com',
    storageBucket: 'pw-f-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt67ZUkDgCelFy2paIuF3xFzk3XBoxSBs',
    appId: '1:903771649579:android:7a26a7aa6e0130addb5c6e',
    messagingSenderId: '903771649579',
    projectId: 'pw-f-crud',
    storageBucket: 'pw-f-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-ZREODFXhq9OIFDEKrKEIMSDFJk6iBw',
    appId: '1:903771649579:ios:1b8d41e1d7372d34db5c6e',
    messagingSenderId: '903771649579',
    projectId: 'pw-f-crud',
    storageBucket: 'pw-f-crud.appspot.com',
    iosBundleId: 'com.example.pwCrudapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn-ZREODFXhq9OIFDEKrKEIMSDFJk6iBw',
    appId: '1:903771649579:ios:d9e01f2bd230a983db5c6e',
    messagingSenderId: '903771649579',
    projectId: 'pw-f-crud',
    storageBucket: 'pw-f-crud.appspot.com',
    iosBundleId: 'com.example.pwCrudapp.RunnerTests',
  );
}
